import CardProyect from '../components/CardProyects'
import Head from 'next/head'
import Link from 'next/link'
import { BsChevronDown, BsLinkedin } from 'react-icons/bs'
import { MdOutlineEmail, MdPictureAsPdf } from 'react-icons/md'
import styles from '../styles/Home.module.css'
export default function Home() {

  return (

    <div className={styles.landing}>
      <Head>
        <title>Portafolio | Marcos Moraga</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.app__container}>
        <div className={styles.app}>
          <header className={styles.landing__header}>
            <div className={styles.landing__header__title}>
              <p>CREATIVO | DESARROLLADOR | ENTUSIASTA</p>
              <h1>MARCOS MORAGA</h1>
            </div>
          </header>
          <main className={styles.landing__main}>
            <div className={styles.landing__main_container}>
              <div className={styles.landing__main_content}>

                <CardProyect />
                <div className={styles.landing__main_card_container}>
                  <div className={styles.landing__main_card}>
                    <div className={styles.landing__main_card_header_img}></div>
                    <div className={styles.landing__main_card_body}>
                      <h2>Sobre Mi</h2>
                      <p>Desarrollador full stack, apasionado por el desarrollo y la innovación, activo y motivado por los nuevos
                        desafíos que pueda encontrar en el ámbito profesional.</p>
                    </div>
                    <div className={styles.landing__main_card_footer}>
                      <a rel='noreferrer' download href="/CVMarcosMoraga.pdf" ><MdPictureAsPdf className={styles.landing__main_card_footer_icon} /></a>
                      <a rel='noreferrer' target='_blank' href="https://www.linkedin.com/in/marcos-moraga-hermosilla"><BsLinkedin className={styles.landing__main_card_footer_linkedin} /></a>
                      <a href="mailto:moraga.dev@gmail.com"><MdOutlineEmail className={styles.landing__main_card_footer_icon} /></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </main>

        </div>
      </div>
      <footer className={styles.landing__footer}>
        <div className={styles.landing__footer_more_about}>
          <Link href="/work">
            <a className={styles.landing__footer_more_about_text}>MÁS INFO
            </a>
          </Link>
        </div>
        <div className={styles.landing__footer_chevron_down}>
          <Link href="/work">
            <a><BsChevronDown className={styles.landing__footer_chevron_down_icon} /></a>
          </Link>
        </div>

      </footer>


    </div >

  )
}
